import { AuthUserProvider } from "@/firebase/auth";
import "./globals.css";
import { Poppins } from "next/font/google";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <AuthUserProvider>
        <body className={poppins.className}>{children}</body>
      </AuthUserProvider>
    </html>
  );
}
